"""
Plain-English session narrative, derived from ledger payloads.

Every line is generated by a template reading recorded fields. No model is
involved at any point — a narrative produced by an LLM would be a claim about
the audit trail rather than a reading of it, and the one thing this panel must
never do is describe a payment that the chain does not evidence.

Each line carries the `seq` of the entry it was derived from, so the operator
view can link every sentence to the row that proves it. A line that cannot name
its seq does not get emitted.
"""

from __future__ import annotations

from server.db.models import LedgerEntry, SessionRecord
from server.ledger.events import EventType

# Operator-facing names for the raw event enum. FORENSIC view keeps the enum.
EVENT_LABELS: dict[str, str] = {
    EventType.INTENT_SIGNED.value: "Spending limit authorised",
    EventType.CATALOG_QUERIED.value: "Agent searched the catalogue",
    EventType.LLM_TIMEOUT.value: "Model call timed out",
    EventType.LLM_RATE_LIMITED.value: "Model provider refused the call",
    EventType.LLM_CALL_FAILED.value: "Model call failed",
    EventType.LLM_KEY_FAILOVER.value: "Switched to a spare provider key",
    EventType.QUOTE_ISSUED.value: "Merchant quoted a price",
    EventType.CART_BUILT.value: "Agent assembled a cart",
    EventType.POLICY_EVALUATED.value: "Policy check",
    EventType.CART_SIGNED.value: "Buyer signed for this exact cart",
    EventType.ORDER_CREATED.value: "Order created at Razorpay",
    EventType.PAYMENT_CAPTURED.value: "Payment captured",
    EventType.PAYMENT_SIMULATED.value: "Payment captured",
    EventType.FULFILMENT_FAILED.value: "Delivery failed",
    EventType.REFUND_INITIATED.value: "Refund attempted",
    EventType.REFUND_FAILED.value: "Refund rejected by provider",
    EventType.REFUND_PENDING_SETTLEMENT.value: "Refund deferred until settlement",
    EventType.REFUND_RETRY_SCHEDULED.value: "Refund retry attempted",
    EventType.REFUND_CONFIRMED.value: "Money returned",
    EventType.REFUND_SIMULATED.value: "Money returned",
    EventType.NO_CART_BUILT.value: "Agent produced no usable cart",
    EventType.LLM_TIMEOUT.value: "Model timed out",
    EventType.SESSION_CLOSED.value: "Session closed",
    EventType.SESSION_STALE.value: "Session stalled",
    EventType.ESCALATED.value: "Held for human review",
    EventType.HUMAN_APPROVED.value: "Human approved",
    EventType.HUMAN_REJECTED.value: "Human rejected",
    EventType.LLM_CALL.value: "Agent consulted its model",
}


def label_for(event_type: str) -> str:
    """Operator-facing label, falling back to a readable form of the enum."""
    if event_type in EVENT_LABELS:
        return EVENT_LABELS[event_type]
    return event_type.replace("_", " ").capitalize()


# ── Formatting ────────────────────────────────────────────────────────────────

def _rupees(paise: int | None) -> str:
    if paise is None:
        return "an unrecorded amount"
    return f"₹{paise / 100:,.2f}".replace(".00", "")


def _duration(ms: int | None) -> str:
    if ms is None:
        return "an unrecorded time"
    if ms < 1000:
        return f"{ms}ms"
    if ms < 60_000:
        return f"{ms / 1000:.1f}s"
    return f"{ms // 60000}m{(ms % 60000) // 1000:02d}s"


# Why each verdict landed, in the operator's language rather than the code's.
_ALLOW_REASON = "within budget, category matches"
_DENY_REASONS = {
    "PER_TXN_CAP": "over per-transaction cap",
    "DAILY_CAP": "over the daily spending cap",
    "CATEGORY_DENY": "category not authorised",
    "ITEM_COUNT": "more items than authorised",
    "MANDATE_INVALID": "the signature on the cart did not verify",
}
_ESCALATE_REASONS = {
    "FIRST_CONTACT_BUYER": "this buyer's first time with this merchant",
    "NEW_MERCHANT": "this buyer's first time with this merchant",
    "PRICE_DRIFT": "price moved well above the estimate",
    "VELOCITY": "too many purchases in a short window",
}


def _verdict_phrase(payload: dict) -> str:
    decision = payload.get("decision")
    code = payload.get("code") or ""
    if decision == "ALLOW":
        return f"ALLOWED ({_ALLOW_REASON})"
    if decision == "DENY":
        return f"DENIED — {_DENY_REASONS.get(code, code.replace('_', ' ').lower())}"
    if decision == "ESCALATE":
        return f"HELD FOR REVIEW — {_ESCALATE_REASONS.get(code, code.replace('_', ' ').lower())}"
    return str(decision or "recorded")


# ── Builder ───────────────────────────────────────────────────────────────────

def _what_would_have_passed(code: str, intent: dict, cart: dict) -> str | None:
    """
    The counterfactual for a denial, read straight off the mandate and the cart.

    Every branch names a threshold that is already recorded — the authorised
    budget, the item limit, the allowed categories — so this states what the
    rule tested rather than guessing at intent. Codes without a well-defined
    boundary get nothing rather than a vague sentence.
    """
    items = cart.get("items") or []
    total = cart.get("total_paise")

    if code == "PER_TXN_CAP":
        budget = intent.get("budget_paise")
        if budget is not None:
            return f"Would have passed at {_rupees(budget)} or less."

    if code == "ITEM_COUNT":
        max_lines = intent.get("max_line_items", intent.get("max_items"))
        if max_lines is not None:
            return (
                f"Would have passed at {max_lines} line item"
                f"{'' if max_lines == 1 else 's'} or fewer "
                f"({len(items)} were proposed). The ceiling counts lines, not "
                f"units."
            )

    if code == "CATEGORY_DENY":
        allowed = set(intent.get("categories") or [])
        offending = [
            i for i in items
            if i.get("category") and i["category"] not in allowed
        ]
        if offending:
            named = ", ".join(
                f"{i.get('name') or i.get('sku_id')} ({i['sku_id']}, {i['category']})"
                for i in offending
            )
            allowed_txt = ", ".join(sorted(allowed)) or "none"
            return (
                f"Blocked by {named}. Would have passed without it — "
                f"authorised categories: {allowed_txt}."
            )

    if code == "DAILY_CAP" and total is not None:
        return (
            "Would have passed on a day with less spend already settled, "
            "or at a smaller cart total."
        )

    return None


def build_narrative(session: SessionRecord, entries: list[LedgerEntry]) -> list[dict]:
    """
    Turn one session's ledger into ordered plain-English lines.

    Returns [{"text": str, "seq": int, "tone": str}], where tone is one of
    neutral | good | bad | hold and drives nothing but colour.
    """
    by_type: dict[str, LedgerEntry] = {}
    for e in entries:
        by_type.setdefault(e.event_type, e)      # first occurrence of each

    def payload(event: EventType) -> dict:
        e = by_type.get(event.value)
        return (e.payload or {}) if e else {}

    def seq(event: EventType) -> int | None:
        e = by_type.get(event.value)
        return e.seq if e else None

    lines: list[dict] = []

    def add(
        text: str,
        at: int | None,
        tone: str = "neutral",
        detail: dict | None = None,
    ) -> None:
        # A sentence with no entry behind it has nothing to link to, and would
        # be an assertion the chain does not support. Drop it.
        if at is not None:
            line = {"text": text, "seq": at, "tone": tone}
            if detail:
                line["detail"] = detail
            lines.append(line)

    # ── Who asked for what ────────────────────────────────────────────────────
    intent_seq = seq(EventType.INTENT_SIGNED)
    goal = (session.goal or "").strip()
    if intent_seq is not None:
        add(f'{session.buyer_id} asked to "{goal}"' if goal
            else f"{session.buyer_id} started a session", intent_seq)

        i = payload(EventType.INTENT_SIGNED)
        categories = ", ".join(i.get("categories") or []) or "any category"
        limit = _rupees(i.get("budget_paise"))
        max_lines = i.get("max_line_items", i.get("max_items"))
        add(
            f"Authorised up to {limit} in category: {categories}"
            + (f", max {max_lines} line items" if max_lines else ""),
            intent_seq,
        )

    # ── What the agent put together ───────────────────────────────────────────
    cart = payload(EventType.CART_BUILT)
    cart_seq = seq(EventType.CART_BUILT)
    cart_items = cart.get("items") or []

    # What the agent looked at before choosing. Derived by comparing the SKUs
    # the catalog returned against the ones that reached the cart — both are
    # already recorded, so nothing has to be inferred.
    catalog = payload(EventType.CATALOG_QUERIED)
    catalog_seq = seq(EventType.CATALOG_QUERIED)
    returned = list(catalog.get("sku_ids_returned") or [])
    chosen = [i.get("sku_id") for i in cart_items if i.get("sku_id")]
    not_chosen = [sku for sku in returned if sku not in set(chosen)]

    if catalog_seq is not None and returned:
        if not_chosen:
            add(
                f"Considered {len(returned)} SKUs, chose {len(chosen)}",
                catalog_seq,
                detail={
                    "kind": "considered",
                    "returned": returned,
                    "chosen": chosen,
                    "not_chosen": not_chosen,
                    "query": catalog.get("query"),
                },
            )
        else:
            # Resolved directly by id: no browsing step happened, and claiming
            # the agent "considered" a wider set would be untrue.
            add(
                f"Resolved {len(returned)} SKU{'' if len(returned) == 1 else 's'} "
                f"directly by id — no catalogue search on this path",
                catalog_seq,
            )

    if cart_seq is not None:
        count = cart.get("item_count") or len(cart_items)
        units = sum(i.get("quantity", 0) for i in cart_items)
        # Lines and units stated separately: the ceiling applies to lines, and
        # a reader seeing only one number cannot tell which was checked.
        qty = f"{count} line item{'' if count == 1 else 's'}"
        if units and units != count:
            qty += f" ({units} units)"
        add(
            f"Agent proposed {qty} "
            f"→ {_rupees(cart.get('total_paise'))}",
            cart_seq,
            detail={
                "kind": "cart",
                "items": cart_items,
                "total_paise": cart.get("total_paise"),
            } if cart_items else None,
        )

    # ── The model call itself failed ─────────────────────────────────────────
    #
    # Same standard as no_cart: name the failure and its cause. An errored
    # session used to read "Considered 28 SKUs, chose 0 / Session closed
    # (error)", which tells a reader that something broke and nothing about
    # what. The cause was on the ledger the whole time, in the closing entry's
    # reason string, and nothing surfaced it.
    _FAILURE_EVENTS = (
        EventType.LLM_TIMEOUT,
        EventType.LLM_RATE_LIMITED,
        EventType.LLM_CALL_FAILED,
    )
    failure = next(
        ((e, by_type[e.value]) for e in _FAILURE_EVENTS if e.value in by_type),
        None,
    )
    if failure is not None:
        event_type, entry = failure
        f = entry.payload or {}
        waited = f.get("waited_ms")
        waited_text = f" after {waited / 1000:.1f}s" if isinstance(waited, (int, float)) else ""

        if event_type is EventType.LLM_TIMEOUT:
            headline = (
                f"Model call timed out{waited_text} "
                f"(limit {f.get('timeout_seconds', '?')}s)."
            )
        elif event_type is EventType.LLM_RATE_LIMITED:
            keys = f.get("keys_tried") or 1
            headline = (
                f"Model provider refused the call: rate limit reached on "
                f"{keys} key{'' if keys == 1 else 's'}"
                + (f", resets in {f.get('resets_in')}" if f.get("resets_in") else "")
                + "."
            )
        else:
            headline = (
                f"Model call failed{waited_text}: "
                f"{f.get('error_type') or 'unknown error'}."
            )

        add(headline, entry.seq, "bad")
        add(
            "No cart was proposed, so no policy decision was made and no money "
            "moved.",
            entry.seq,
            "neutral",
        )
        detail = f.get("detail")
        if detail:
            add(f"Provider said: {detail[:160]}", entry.seq, "neutral")

    # ── The agent came back with nothing ─────────────────────────────────────
    no_cart = payload(EventType.NO_CART_BUILT)
    no_cart_seq = seq(EventType.NO_CART_BUILT)
    if no_cart_seq is not None:
        proposed = no_cart.get("proposed_skus") or []

        # Say what was searched and why nothing matched.
        #
        # "no usable cart" on its own reads as a broken system. It is the
        # opposite: the agent was shown the merchant's inventory, found nothing
        # answering the request, and declined to invent a product rather than
        # buying the nearest thing. Naming the search and its size is what
        # turns a dead end into a visibly correct refusal.
        search = payload(EventType.CATALOG_QUERIED)
        search_seq = seq(EventType.CATALOG_QUERIED)
        shown = search.get("result_count")
        category = (search.get("filters") or {}).get("category")
        asked = search.get("query")

        if shown is not None:
            add(
                f"Searched {shown} {category + ' ' if category else ''}SKU"
                f"{'' if shown == 1 else 's'}"
                + (f", no match for “{asked}”" if asked else ", nothing matched"),
                search_seq if search_seq is not None else no_cart_seq,
                "bad",
            )

        add(
            "The catalogue is the merchant's inventory, and the agent cannot "
            "buy outside it — so it bought nothing."
            + (f" It proposed {', '.join(proposed)}, which the catalogue "
               f"does not stock." if proposed else ""),
            no_cart_seq,
            "bad",
        )
        add("No money moved, and no policy decision was needed: there was "
            "nothing to evaluate.", no_cart_seq, "neutral")

    # ── The gate ──────────────────────────────────────────────────────────────
    verdict = payload(EventType.POLICY_EVALUATED)
    verdict_seq = seq(EventType.POLICY_EVALUATED)
    if verdict_seq is not None:
        decision = verdict.get("decision")
        tone = "good" if decision == "ALLOW" else "bad" if decision == "DENY" else "hold"

        # A denial reads better with the two numbers side by side.
        if decision == "DENY" and cart.get("total_paise") is not None:
            budget = payload(EventType.INTENT_SIGNED).get("budget_paise")
            if budget is not None:
                add(
                    f"Agent proposed {_rupees(cart.get('total_paise'))} "
                    f"against a {_rupees(budget)} budget",
                    verdict_seq,
                    "bad",
                )

        add(f"Policy check: {_verdict_phrase(verdict)}", verdict_seq, tone)

        if decision == "DENY":
            counterfactual = _what_would_have_passed(
                verdict.get("code") or "",
                payload(EventType.INTENT_SIGNED),
                cart,
            )
            if counterfactual:
                add(counterfactual, verdict_seq, "neutral")

    # ── Held for a human ──────────────────────────────────────────────────────
    esc_seq = seq(EventType.ESCALATED)
    if esc_seq is not None:
        add("Held for human review. No money moved while waiting.", esc_seq, "hold")

    if seq(EventType.HUMAN_APPROVED) is not None:
        who = payload(EventType.HUMAN_APPROVED).get("resolved_by") or "an operator"
        add(f"Approved by {who}", seq(EventType.HUMAN_APPROVED), "good")
    if seq(EventType.HUMAN_REJECTED) is not None:
        who = payload(EventType.HUMAN_REJECTED).get("resolved_by") or "an operator"
        add(f"Rejected by {who}. No money moved.", seq(EventType.HUMAN_REJECTED), "bad")

    # ── Offers ────────────────────────────────────────────────────────────────
    offer = payload(EventType.UPSELL_PROPOSED)
    offer_seq = seq(EventType.UPSELL_PROPOSED)
    accepted = payload(EventType.UPSELL_ACCEPTED)
    accepted_seq = seq(EventType.UPSELL_ACCEPTED)
    rejected = payload(EventType.UPSELL_REJECTED)
    rejected_seq = seq(EventType.UPSELL_REJECTED)

    timeout_seq = seq(EventType.LLM_TIMEOUT)
    if timeout_seq is not None:
        t = payload(EventType.LLM_TIMEOUT)
        add(
            f"Model did not answer within {t.get('timeout_seconds')}s — "
            "continued without an offer.",
            timeout_seq,
            "hold",
        )

    if offer_seq is None and timeout_seq is None:
        # Only say this once the session got far enough to have been offered
        # anything at all.
        if verdict.get("decision") == "ALLOW":
            add("No offer was made.", verdict_seq, "neutral")
    elif offer.get("blocked"):
        add(
            f"Offer withheld: {offer.get('name') or offer.get('sku_id')} at "
            f"{_rupees(offer.get('price_paise'))} exceeded the "
            f"{_rupees(offer.get('headroom_paise'))} remaining headroom.",
            offer_seq,
            "hold",
        )
    else:
        add(
            f"Offer: {offer.get('name') or offer.get('sku_id')} at "
            f"{_rupees(offer.get('price_paise'))} — headroom was "
            f"{_rupees(offer.get('headroom_paise'))}",
            offer_seq,
            "neutral",
        )
        if accepted_seq is not None:
            add(
                f"Offer accepted. Cart total "
                f"{_rupees(accepted.get('cart_total_before_paise'))} → "
                f"{_rupees(accepted.get('cart_total_after_paise'))}, still inside "
                f"the authorised limit.",
                accepted_seq,
                "good",
            )
            # The signature that covers the larger cart.
            resigned = next(
                (
                    e for e in entries
                    if e.event_type == EventType.CART_SIGNED.value
                    and (e.payload or {}).get("resigned_after_upsell")
                ),
                None,
            )
            if resigned is not None:
                add(
                    f"Cart re-signed at the new total of "
                    f"{_rupees((resigned.payload or {}).get('total_paise'))}.",
                    resigned.seq,
                    "good",
                )
        elif rejected_seq is not None:
            reason = rejected.get("reason") or "declined"
            add(
                "Offer declined by the buyer." if reason == "declined_by_buyer"
                else f"Offer not taken up ({reason.replace('_', ' ')}).",
                rejected_seq,
                "neutral",
            )

    # ── Money ─────────────────────────────────────────────────────────────────
    signed_seq = seq(EventType.CART_SIGNED)
    order_seq = seq(EventType.ORDER_CREATED)
    pay_entry = by_type.get(EventType.PAYMENT_CAPTURED.value) or by_type.get(
        EventType.PAYMENT_SIMULATED.value
    )

    if pay_entry is not None:
        done = [p for p in ("Cart signed" if signed_seq else None,
                            "order created" if order_seq else None,
                            "payment captured") if p]
        # Anchored on the payment: it is the step a reader will want to check.
        add(", ".join(done), pay_entry.seq, "good")
    elif order_seq is not None:
        add("Cart signed, order created — awaiting payment", order_seq)
    elif signed_seq is not None:
        add("Buyer signed for this exact cart", signed_seq)

    # ── Failure and compensation, in the same voice ───────────────────────────
    fail_seq = seq(EventType.FULFILMENT_FAILED)
    if fail_seq is not None:
        add("Delivery failed after payment.", fail_seq, "bad")

    # A rejected refund is read first and separately.
    #
    # The compensating leg of a saga is the part that is assumed to work, so it
    # is the part worth stating loudly when it does not. Falling through to the
    # "money returned" line because a REFUND_INITIATED exists would tell an
    # operator the buyer had been repaid when the provider had just refused to
    # repay them — the single most expensive sentence this panel could print.
    refund_failed = by_type.get(EventType.REFUND_FAILED.value)
    refund_entry = (
        by_type.get(EventType.REFUND_CONFIRMED.value)
        or by_type.get(EventType.REFUND_SIMULATED.value)
    )

    # Deferred for settlement, which is not the same as refused.
    pending = by_type.get(EventType.REFUND_PENDING_SETTLEMENT.value)
    if pending is not None:
        d = pending.payload or {}
        amount = _rupees(d.get("amount_paise"))
        expected = (d.get("settlement") or {}).get("expected_at") or d.get("retry_after")
        if fail_seq is None:
            add("Order could not be fulfilled after payment.", pending.seq, "bad")
        add(
            "Refund attempted - provider rejected: payment not yet settled, "
            "no balance available."
            + (f" Expected settlement {expected}." if expected else ""),
            pending.seq,
            "bad",
        )
        add(
            f"{amount} is still owed to the buyer. The refund is queued and "
            f"will be retried after settlement - this session is not closed.",
            pending.seq,
            "hold",
        )
    elif refund_failed is not None:
        f = refund_failed.payload or {}
        amount = _rupees(f.get("amount_paise"))
        code = f.get("error_code") or "no error code returned"
        status = f.get("status_code")
        if fail_seq is None:
            add("Order could not be fulfilled after payment.", refund_failed.seq, "bad")
        add(
            f"Refund attempted - rejected by provider "
            f"({code}{f', HTTP {status}' if status else ''}).",
            refund_failed.seq,
            "bad",
        )
        add(
            f"{amount} is still with the provider. Payment "
            f"{f.get('razorpay_payment_id') or 'unknown'} was not reversed; "
            f"the buyer has not been repaid.",
            refund_failed.seq,
            "bad",
        )
    elif refund_entry is not None:
        amount = _rupees((refund_entry.payload or {}).get("amount_paise"))
        if fail_seq is None:
            add("Order could not be fulfilled after payment.", refund_entry.seq, "bad")
        add(f"{amount} returned to the buyer.", refund_entry.seq, "good")
    elif by_type.get(EventType.REFUND_INITIATED.value) is not None:
        # Initiated with neither outcome recorded: say only that much.
        init = by_type[EventType.REFUND_INITIATED.value]
        amount = _rupees((init.payload or {}).get("amount_paise"))
        add(f"Refund of {amount} initiated - no outcome recorded yet.",
            init.seq, "neutral")

    # ── Stalled ───────────────────────────────────────────────────────────────
    stale_seq = seq(EventType.SESSION_STALE)
    if stale_seq is not None:
        s = payload(EventType.SESSION_STALE)
        add(
            f"Session stopped making progress and was marked stale after "
            f"{s.get('stalled_for_seconds', '?')}s idle. No money moved.",
            stale_seq,
            "bad",
        )

    # ── Close ─────────────────────────────────────────────────────────────────
    closed = payload(EventType.SESSION_CLOSED)
    closed_seq = seq(EventType.SESSION_CLOSED)
    if closed_seq is not None:
        state = closed.get("terminal_state") or closed.get("final_status") or "closed"
        duration = _duration(closed.get("duration_ms"))

        # SESSION_CLOSED is written when the payment lands. A fulfilment failure
        # and an unpaid refund come *after* it, so the stored terminal_state is
        # stale by the time those exist — and reading it back verbatim printed
        # "Delivered." directly beneath "the buyer has not been repaid".
        # The outstanding obligation wins: it is the later fact and the one that
        # is still true.
        if pending is not None:
            add(
                f"Session ran {duration} and remains open: the refund has not "
                f"been made.",
                pending.seq,
                "hold",
            )
        elif refund_failed is not None:
            add(
                f"Session ran {duration}. It is closed, but the buyer was not "
                f"repaid.",
                refund_failed.seq,
                "bad",
            )
        elif state == "captured":
            add(f"Delivered. Session closed in {duration}.", closed_seq, "good")
        elif state == "refunded":
            add(f"Session closed in {duration}, buyer made whole.", closed_seq, "good")
        elif state == "failed":
            add(f"No money moved. Session closed in {duration}.", closed_seq, "bad")
        elif state in ("error", "rate_limited") and failure is None:
            # The cause was recorded on the closing entry but nowhere else.
            #
            # Sessions that errored before the failure events existed carry
            # their reason only here, as "agent_error: APITimeoutError: Request
            # timed out." Reading it back is the difference between a session
            # that explains itself and one that says "error" and stops.
            raw = str(closed.get("reason") or "").strip()
            cause = raw.split(":", 1)[1].strip() if raw.startswith("agent_error:") else raw
            add(
                f"Session failed in {duration}"
                + (f" — {cause[:160]}" if cause else " with no recorded cause"),
                closed_seq,
                "bad",
            )
            add(
                "No cart was proposed, so no policy decision was made and no "
                "money moved.",
                closed_seq,
                "neutral",
            )
        else:
            add(f"Session closed ({state}) in {duration}.", closed_seq)

    # A denied session that closed already says "no money moved"; one that was
    # denied and never closed still needs the reassurance stated.
    if (
        verdict.get("decision") == "DENY"
        and closed_seq is None
        and verdict_seq is not None
    ):
        add("No money moved.", verdict_seq, "bad")

    # Told in ledger order, not in the order the sections happen to be written.
    #
    # The refund block is composed before the closing block, but a refund
    # recorded later carries a higher seq — so the story jumped backwards, and
    # the seq links a reader clicks through ran out of order against the chain
    # they point into. Sorting is stable, so lines sharing one seq keep the
    # order they were added in.
    return sorted(lines, key=lambda line: line["seq"])
