"""
Mandate issuer + verifier tests.

These tests use an in-memory SQLite DB (from conftest.py's test_db fixture)
and real ES256 keypairs (auto-generated by conftest.py's _ensure_keys fixture).
No Razorpay calls, no LLM calls.
"""

from __future__ import annotations

import time
from datetime import datetime, timedelta

import pytest

from server.mandate.issuer import sign_cart, sign_intent
from server.mandate.schema import Cart, CartItem
from server.mandate.verifier import record_intent_jti, verify_cart_mandate


# ── Helpers ───────────────────────────────────────────────────────────────────

def _sample_cart(merchant_id: str = "merch_test") -> Cart:
    return Cart(
        merchant_id=merchant_id,
        items=[
            CartItem(sku_id="GRO001", name="Rice 5kg", category="grocery", quantity=1, unit_price_paise=29900),
            CartItem(sku_id="GRO002", name="Atta 10kg", category="grocery", quantity=1, unit_price_paise=45000),
        ],
    )


def _setup_intent_in_db(db, budget_paise: int = 200_000) -> tuple[str, str]:
    """Sign an intent, record its JTI, return (token, jti)."""
    token, mandate = sign_intent(
        buyer_id="buyer_test",
        merchant_id="merch_test",
        budget_paise=budget_paise,
        categories=["grocery"],
        max_items=5,
        estimate_paise=100_000,
    )
    record_intent_jti(
        jti=mandate.jti,
        expires_at=datetime.utcfromtimestamp(mandate.exp),
        db=db,
        session_id="sess_test",
    )
    return token, mandate.jti


# ── Tests: sign + verify happy path ──────────────────────────────────────────

class TestSignAndVerify:
    def test_valid_cart_mandate_verifies(self, test_db):
        _, intent_jti = _setup_intent_in_db(test_db)
        cart = _sample_cart()
        token, mandate = sign_cart(intent_jti=intent_jti, cart=cart)

        result = verify_cart_mandate(token, cart, test_db, session_id="sess_test")
        assert result.valid is True
        assert result.reason == "ok"
        assert result.cart_mandate_claims["cart_hash"] == cart.canonical_hash()

    def test_cart_hash_is_deterministic(self):
        cart1 = _sample_cart()
        cart2 = _sample_cart()
        assert cart1.canonical_hash() == cart2.canonical_hash()

    def test_cart_hash_changes_with_price(self):
        cart1 = Cart(
            merchant_id="m",
            items=[CartItem(sku_id="A", name="X", category="c", quantity=1, unit_price_paise=100)],
        )
        cart2 = Cart(
            merchant_id="m",
            items=[CartItem(sku_id="A", name="X", category="c", quantity=1, unit_price_paise=101)],
        )
        assert cart1.canonical_hash() != cart2.canonical_hash()


# ── Tests: verifier failure cases ────────────────────────────────────────────

class TestVerifierFailures:
    def test_expired_token_rejected(self, test_db):
        _, intent_jti = _setup_intent_in_db(test_db)
        cart = _sample_cart()
        # Sign with ttl_seconds=-1 so it's already expired
        token, _ = sign_cart(intent_jti=intent_jti, cart=cart, ttl_seconds=-1)

        result = verify_cart_mandate(token, cart, test_db)
        assert result.valid is False
        assert "expired" in result.reason

    def test_cart_hash_mismatch_rejected(self, test_db):
        _, intent_jti = _setup_intent_in_db(test_db)
        original_cart = _sample_cart()
        token, _ = sign_cart(intent_jti=intent_jti, cart=original_cart)

        # Present a different cart
        tampered_cart = Cart(
            merchant_id="merch_test",
            items=[
                CartItem(sku_id="GRO001", name="Rice 5kg", category="grocery", quantity=1, unit_price_paise=1),
            ],
        )
        result = verify_cart_mandate(token, tampered_cart, test_db)
        assert result.valid is False
        assert result.reason == "cart_hash_mismatch"

    def test_replay_rejected(self, test_db):
        _, intent_jti = _setup_intent_in_db(test_db)
        cart = _sample_cart()
        token, _ = sign_cart(intent_jti=intent_jti, cart=cart)

        # First use succeeds
        result1 = verify_cart_mandate(token, cart, test_db, session_id="sess_1")
        assert result1.valid is True

        # Re-create the DB session to avoid caching
        # Second use of the same JTI is rejected by the UNIQUE constraint
        result2 = verify_cart_mandate(token, cart, test_db, session_id="sess_2")
        assert result2.valid is False
        assert result2.reason == "jti_replayed"

    def test_unknown_intent_jti_rejected(self, test_db):
        cart = _sample_cart()
        # Sign cart referencing an intent JTI that was never recorded
        token, _ = sign_cart(intent_jti="nonexistent-intent-jti", cart=cart)

        result = verify_cart_mandate(token, cart, test_db)
        assert result.valid is False
        assert result.reason == "intent_jti_not_found"

    def test_garbled_token_rejected(self, test_db):
        cart = _sample_cart()
        result = verify_cart_mandate("not.a.jwt", cart, test_db)
        assert result.valid is False
        assert "jwt_error" in result.reason

    def test_wrong_typ_rejected(self, test_db):
        # Sign an intent mandate, try to use it as a cart mandate
        token, _ = sign_intent(
            buyer_id="b",
            merchant_id="m",
            budget_paise=100_000,
            categories=["grocery"],
            max_items=5,
            estimate_paise=80_000,
        )
        cart = _sample_cart()
        result = verify_cart_mandate(token, cart, test_db)
        assert result.valid is False
        assert result.reason == "wrong_typ"


# ── Tests: record_intent_jti ────────────────────────────────────────────────

class TestRecordIntentJti:
    def test_first_record_succeeds(self, test_db):
        ok = record_intent_jti(
            jti="unique-jti-abc",
            expires_at=datetime.utcnow() + timedelta(minutes=15),
            db=test_db,
        )
        assert ok is True

    def test_duplicate_jti_returns_false(self, test_db):
        jti = "dup-jti-xyz"
        exp = datetime.utcnow() + timedelta(minutes=15)
        record_intent_jti(jti=jti, expires_at=exp, db=test_db)
        ok = record_intent_jti(jti=jti, expires_at=exp, db=test_db)
        assert ok is False
