import type { ReactNode } from 'react'
import { useState } from 'react'
import type { NarrativeDetail, NarrativeResponse, SessionRow } from '../api'
import { Panel, PanelMessage } from '../components/Panel'
import { StatusChip } from '../components/StatusChip'
import { formatElapsed, formatPaise, shortId } from '../format'

/*
  Operator view — the same session, told as a story.

  Every line comes from GET /sessions/{id}/narrative, which templates it from
  ledger payloads server-side. No model writes any of this: a narrative
  generated by an LLM would be a claim *about* the audit trail rather than a
  reading *of* it, and this panel's whole value is that it cannot drift from
  what the chain records.

  Each line ends with the seq it was derived from, and that seq is a button.
  Clicking it switches to FORENSIC, filters to this session and expands that
  exact row. Plain story on top, cryptographic proof one click below — the link
  is the point of the whole layer.
*/

const TONE: Record<string, string> = {
  good: 'text-state-allow',
  bad: 'text-state-deny',
  hold: 'text-state-escalate',
  neutral: 'text-ink-100',
}

const MARKER: Record<string, string> = {
  good: 'bg-state-allow',
  bad: 'bg-state-deny',
  hold: 'bg-state-escalate',
  neutral: 'bg-ink-600',
}

/*
  Cart contents, straight from the CART_BUILT payload.

  A merchant asking "what was actually bought" should not have to open the
  forensic view to find out. Every column here is a recorded field — the line
  total is the one the ledger stored, not one recomputed in the browser, so if
  the two ever disagreed this table would show it rather than paper over it.
*/
function CartTable({ detail }: { detail: NarrativeDetail }) {
  const items = detail.items ?? []
  if (!items.length) return null

  return (
    <div className="mt-1.5 mb-1 border border-ink-700">
      <div className="grid grid-cols-[62px_1fr_28px_74px_78px] gap-1 border-b border-ink-700 bg-ink-850 px-1.5 py-0.5 t-meta font-semibold tracking-[0.08em] text-ink-400 uppercase">
        <span>sku</span>
        <span>name</span>
        <span className="text-right">qty</span>
        <span className="text-right">unit</span>
        <span className="text-right">line total</span>
      </div>

      {items.map((item) => (
        <div
          key={item.sku_id}
          className="grid grid-cols-[62px_1fr_28px_74px_78px] gap-1 border-b border-ink-700/60 px-1.5 py-0.5 t-meta last:border-b-0"
        >
          <span className="tabular truncate text-ink-400">{item.sku_id}</span>
          <span className="truncate text-ink-200" title={item.name}>
            {item.name ?? item.sku_id}
          </span>
          <span className="tabular text-right text-ink-300">{item.quantity}</span>
          <span className="tabular text-right text-ink-300">
            {formatPaise(item.unit_price_paise)}
          </span>
          <span className="tabular text-right text-ink-100">
            {formatPaise(
              item.line_total_paise ?? item.unit_price_paise * item.quantity,
            )}
          </span>
        </div>
      ))}

      <div className="grid grid-cols-[62px_1fr_28px_74px_78px] gap-1 border-t border-ink-600 bg-ink-850 px-1.5 py-0.5 t-meta">
        <span />
        <span />
        <span />
        <span className="text-right font-semibold tracking-[0.06em] text-ink-400 uppercase">
          total
        </span>
        <span className="tabular text-right font-bold text-ink-050">
          {formatPaise(detail.total_paise)}
        </span>
      </div>
    </div>
  )
}

/** The SKUs the agent saw and passed over. Collapsed by default. */
function ConsideredList({ detail }: { detail: NarrativeDetail }) {
  const [open, setOpen] = useState(false)
  const notChosen = detail.not_chosen ?? []
  if (!notChosen.length) return null

  return (
    <div className="mt-1 mb-1">
      <button
        onClick={() => setOpen((v) => !v)}
        className="border border-ink-700 px-1.5 py-0.5 t-meta text-ink-400 hover:border-accent/50 hover:text-accent"
      >
        {open ? '▾' : '▸'} {notChosen.length} not chosen
      </button>
      {open ? (
        <div className="mt-1 flex flex-wrap gap-1 border border-ink-700 bg-ink-900 p-1.5">
          {notChosen.map((sku) => (
            <span
              key={sku}
              className="tabular border border-ink-700 px-1 t-meta text-ink-400"
            >
              {sku}
            </span>
          ))}
        </div>
      ) : null}
    </div>
  )
}

interface Props {
  session: SessionRow | null
  narrative: NarrativeResponse | null
  error: string | null
  onJumpToSeq: (sessionId: string, seq: number) => void
  /** Shown in place of the narrative while no session is selected. */
  landing: ReactNode
}

export function OperatorView({
  session,
  narrative,
  error,
  onJumpToSeq,
  landing,
}: Props) {
  return (
    <Panel
      title={session ? `Session · ${shortId(session.session_id)}` : 'Session narrative'}
      caption="What happened, in plain English. Every line links to the ledger entry that proves it."
      className="min-w-0 flex-1"
      aside={
        session ? (
          <>
            <StatusChip
              status={
                session.has_pending_escalation && session.status === 'active'
                  ? 'escalated'
                  : session.status
              }
            />
            <span className="tabular">{formatElapsed(session.elapsed_ms)}</span>
          </>
        ) : null
      }
    >
      {!session ? (
        // The landing state, passed in rather than built here: it needs
        // /metrics and /ledger/verify, which this panel has no reason to know
        // about once a session is selected.
        landing
      ) : !narrative ? (
        <PanelMessage tone={error ? 'error' : 'muted'}>
          {error ? `narrative unavailable — ${error}` : <span className="pulse">reading the ledger…</span>}
        </PanelMessage>
      ) : narrative.lines.length === 0 ? (
        <PanelMessage>
          this session has no ledger entries yet
          <br />
          <span className="text-ink-400">nothing has been recorded to describe</span>
        </PanelMessage>
      ) : (
        <div className="min-h-0 flex-1 overflow-y-auto px-4 pb-4">
          <ol className="flex flex-col">
            {narrative.lines.map((line, i) => (
              <li
                key={`${line.seq}-${i}`}
                className="group relative flex items-start gap-3 py-[5px]"
              >
                {/* Spine: a vertical rule joining the beats of the story. */}
                <span className="relative flex w-3 shrink-0 justify-center self-stretch">
                  {i < narrative.lines.length - 1 ? (
                    <span className="absolute top-4 bottom-[-6px] w-px bg-ink-700" />
                  ) : null}
                  <span
                    className={`relative z-10 mt-[9px] size-1.5 shrink-0 rounded-full ${
                      MARKER[line.tone] ?? MARKER.neutral
                    }`}
                  />
                </span>

                <span
                  className={`t-narrative min-w-0 flex-1 ${
                    TONE[line.tone] ?? TONE.neutral
                  }`}
                >
                  {line.text}
                  {line.detail?.kind === 'cart' ? (
                    <CartTable detail={line.detail} />
                  ) : null}
                  {line.detail?.kind === 'considered' ? (
                    <ConsideredList detail={line.detail} />
                  ) : null}
                </span>

                <button
                  onClick={() => onJumpToSeq(narrative.session_id, line.seq)}
                  title={`Show ledger entry ${line.seq} in FORENSIC view — the record this line was read from`}
                  className="t-transition t-focus tabular mt-[3px] shrink-0 border border-transparent px-2 py-0.5 t-meta text-ink-400 hover:border-accent/50 hover:text-accent"
                >
                  seq {line.seq}
                </button>
              </li>
            ))}
          </ol>

          <p className="mt-3 border-t border-ink-700 pt-2 t-meta leading-snug text-ink-400">
            Written from ledger payloads by a template, not by a language model.
            Click any seq to see the signed entry it was read from.
          </p>
        </div>
      )}
    </Panel>
  )
}
