"""
SQLAlchemy models.

Critical constraints:
  - MandateJti has a DB-level UNIQUE(jti) — this is the authoritative replay
    prevention guard. App-level check-then-insert would have a TOCTOU race.
  - LedgerEntry.seq is monotonically increasing and globally unique.
  - All monetary amounts are stored in paise (integer), never floats.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    DateTime,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


def _uuid() -> str:
    return str(uuid.uuid4())


class Base(DeclarativeBase):
    pass


# ── Sessions ──────────────────────────────────────────────────────────────────

class SessionRecord(Base):
    """One end-to-end buyer session."""

    __tablename__ = "sessions"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    buyer_id: Mapped[str] = mapped_column(String(64), nullable=False)
    merchant_id: Mapped[str] = mapped_column(String(64), nullable=False)
    goal: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    budget_paise: Mapped[int] = mapped_column(BigInteger, nullable=False)
    status: Mapped[str] = mapped_column(String(20), default="active")

    # Razorpay IDs populated as the saga progresses
    razorpay_order_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    razorpay_payment_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    razorpay_refund_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (Index("ix_sessions_status", "status"),)


# ── Ledger ────────────────────────────────────────────────────────────────────

class LedgerEntry(Base):
    """Append-only hash-chained ledger. Written before side effects, confirmed after."""

    __tablename__ = "ledger_entries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    seq: Mapped[int] = mapped_column(Integer, unique=True, nullable=False)
    ts: Mapped[str] = mapped_column(String(32), nullable=False)          # ISO-8601 UTC
    session_id: Mapped[str] = mapped_column(String(36), nullable=False)
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)
    payload: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    prev_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    hash: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # True when this entry was produced by the eval harness replaying fixture IDs.
    # Never true in a live run.
    replayed_from_fixture: Mapped[bool] = mapped_column(Boolean, default=False)

    __table_args__ = (
        Index("ix_ledger_session_id", "session_id"),
        Index("ix_ledger_seq", "seq"),
    )


# ── Mandate JTI replay store ──────────────────────────────────────────────────

class MandateJti(Base):
    """
    Tracks every mandate JTI that has been presented for verification.

    The DB-level UNIQUE constraint on `jti` is the authoritative replay guard.
    An IntegrityError on insert means replay; the app converts that into
    VerifyResult(valid=False, reason="jti_replayed") without a second DB round-trip.
    """

    __tablename__ = "mandate_jtis"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    jti: Mapped[str] = mapped_column(String(36), nullable=False)
    jti_type: Mapped[str] = mapped_column(String(16), nullable=False)   # "intent" | "cart"
    session_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (
        # DB-level uniqueness — not just an app-level check
        UniqueConstraint("jti", name="uq_mandate_jti"),
    )


# ── Quote records ─────────────────────────────────────────────────────────────

class QuoteRecord(Base):
    """Server-side quote generated by get_quote(). Has a 300-second TTL."""

    __tablename__ = "quotes"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    session_id: Mapped[str] = mapped_column(String(36), nullable=False)
    sku_ids: Mapped[list] = mapped_column(JSON, nullable=False)
    quantities: Mapped[list] = mapped_column(JSON, nullable=False)
    items: Mapped[list] = mapped_column(JSON, nullable=False)        # itemised cart rows
    total_paise: Mapped[int] = mapped_column(BigInteger, nullable=False)
    cart_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    used: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (Index("ix_quotes_session_id", "session_id"),)


# ── Escalation requests ───────────────────────────────────────────────────────

class EscalationRequest(Base):
    """
    Raised when the policy engine returns ESCALATE.
    The session blocks until a human approves or rejects via the dashboard.
    """

    __tablename__ = "escalation_requests"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    session_id: Mapped[str] = mapped_column(String(36), nullable=False)
    reason_code: Mapped[str] = mapped_column(String(32), nullable=False)
    detail: Mapped[str] = mapped_column(Text, nullable=False)
    intent_snapshot: Mapped[dict] = mapped_column(JSON, nullable=False)
    cart_snapshot: Mapped[dict] = mapped_column(JSON, nullable=False)
    status: Mapped[str] = mapped_column(String(16), default="pending")

    resolved_by: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (
        Index("ix_escalation_session_id", "session_id"),
        Index("ix_escalation_status", "status"),
    )
